services:
  pve-corosync-qdevice-voter:
    image: 0xygen1337/pve-corosync-qdevice-voter:latest
    ports:
      - "22:22"
    environment:
      - ROOT_PASSWORD=${ROOT_PASSWORD}
    volumes:
      - ./corosync-data:/etc/corosync
    restart: unless-stopped